export interface ResLogin {
  usuario: Usuario;
  token: string;
}

export interface Usuario {
  rol: string;
  estado: boolean;
  google: boolean;
  nombre: string;
  correo: string;
  uid: string;
  img: string;
}

export interface SignUpData {
  correo: string;
  password: string;
  nombre: string;
}

export interface SignInData {
  correo: string;
  password: string;
}

export interface ResProductos {
  total: number;
  productos: Producto[];
}

export interface Producto {
  precio: number;
  cambio: boolean;
  imgs: string[];
  _id: string;
  nombre: string;
  categoria: Categoria;
  genero: Categoria;
  descripcion: string;
  usuario: Usuario;
}

export interface Categoria {
  _id: string;
  nombre: string;
}

export interface MessageChat {
  _id: string;
  chatId: string;
  senderId: string;
  text: string;
  createdAt: string;
  updatedAt: string;
  __v: number;
}

export interface UserChat {
  members: string[];
  _id: string;
  createdAt: string;
  updatedAt: string;
  __v: number;
}

export interface Categorias {
  total: number;
  categorias: InfoCategoria[];
}

export interface InfoCategoria {
  _id: string;
  nombre: string;
  usuario: InfoUsuario;
}

export interface InfoUsuario {
  _id: string;
  nombre: string;
}

export interface ResPublishProduct {
  precio: number;
  _id: string;
  nombre: string;
  categoria: Categoria;
  usuario: InfoUsuario;
  genero: string;
  descripcion: string;
  imgs: string[];
  cambio: Boolean;
}

// Generated by https://quicktype.io

export interface Genero {
  _id: string;
  nombre: string;
  categoria: string;
  usuario: string;
}
